USE RIS_HRO;
GO

SELECT DB_NAME() AS BaseActual;

SELECT 'CAT_USUARIOS' Tabla, COUNT(*) Registros FROM dbo.CAT_USUARIOS
UNION ALL SELECT 'CAT_PACIENTES', COUNT(*) FROM dbo.CAT_PACIENTES
UNION ALL SELECT 'CAT_MEDICOS', COUNT(*) FROM dbo.CAT_MEDICOS
UNION ALL SELECT 'CAT_PRUEBAS', COUNT(*) FROM dbo.CAT_PRUEBAS
UNION ALL SELECT 'CAPACIDAD', COUNT(*) FROM dbo.CAPACIDAD
UNION ALL SELECT 'CITA', COUNT(*) FROM dbo.CITA
UNION ALL SELECT 'DETALLE_CITA', COUNT(*) FROM dbo.DETALLE_CITA;

EXEC dbo.sp_Dashboard_ResumenDia @Fecha=CAST(GETDATE() AS DATE);
EXEC dbo.sp_Dashboard_CapacidadDia @Fecha=CAST(GETDATE() AS DATE);
EXEC dbo.sp_Dashboard_ProximasCitas @Fecha=CAST(GETDATE() AS DATE);
GO
